import './globals.css'

export const metadata = {
  title: 'Food App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
(<style>
    @import url('https://fonts.googleapis.com/css2?family=Cabin:ital,wght@0,400;0,500;0,600;1,600&family=Roboto:ital@1&display=swap');
  </style>)
  return (
    <html lang="en">
      <body>
      <div className=' mt-[20px] h-[896px] w-[414px] m-auto bg-[#f2f2f2] shadow-2xl'>
        {children}
      </div>  
      </body>
    </html>
  )
}
